name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [web, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd ${{ matrix.project }}
          npm install --legacy-peer-deps

      - name: Run tests
        run: |
          cd ${{ matrix.project }}
          if [ "${{ matrix.project }}" == "web" ]; then npx playwright install; fi
          npm test

      - name: Build project
        run: |
          cd ${{ matrix.project }}
          npm run build
